--------------------------- REGIONES ---------------------------
INSERT INTO REGION VALUES(1, 'Arica y Parinacota');
INSERT INTO REGION VALUES(2, 'Tarapacá');
INSERT INTO REGION VALUES(3, 'Antofagasta');
INSERT INTO REGION VALUES(4, 'Atacama');
INSERT INTO REGION VALUES(5, 'Coquimbo');
INSERT INTO REGION VALUES(6, 'Valparaiso');
INSERT INTO REGION VALUES(7, 'Metropolitana de Santiago');
INSERT INTO REGION VALUES(8, 'Libertador General Bernardo O’Higgins');
INSERT INTO REGION VALUES(9, 'Maule');
INSERT INTO REGION VALUES(10, 'Ñuble');
INSERT INTO REGION VALUES(11, 'Biobío');
INSERT INTO REGION VALUES(12, 'La Araucanía');
INSERT INTO REGION VALUES(13, 'Los Ríos');
INSERT INTO REGION VALUES(14, 'Los Lagos');
INSERT INTO REGION VALUES(15, 'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO REGION VALUES(16, 'Magallanes y la Antártica Chilena');


--------------------- PROVINCIAS POR REGION ---------------------
-- ARICA Y PARINACOTA 
INSERT INTO PROVINCIA VALUES(1, 'Arica', 1);
INSERT INTO PROVINCIA VALUES(2, 'Parinacota', 1);

-- TARAPACÁ
INSERT INTO PROVINCIA VALUES(3, 'Iquique', 2);
INSERT INTO PROVINCIA VALUES(4, 'Tamarugal', 2);

-- ANTOFAGASTA
INSERT INTO PROVINCIA VALUES(5, 'Antofagasta', 3);
INSERT INTO PROVINCIA VALUES(6, 'El Loa', 3);
INSERT INTO PROVINCIA VALUES(7, 'Tocopilla', 3);

-- ATACAMA
INSERT INTO PROVINCIA VALUES(8, 'Copiapó', 4);
INSERT INTO PROVINCIA VALUES(9, 'Chañaral', 4);
INSERT INTO PROVINCIA VALUES(10, 'Huasco', 4);

-- COQUIMBO
INSERT INTO PROVINCIA VALUES(11, 'Elqui', 5);
INSERT INTO PROVINCIA VALUES(12, 'Choapa', 5);
INSERT INTO PROVINCIA VALUES(13, 'Limarí', 5);

-- VALPARAISO
INSERT INTO PROVINCIA VALUES(14, 'Valparaíso', 6);
INSERT INTO PROVINCIA VALUES(15, 'Isla De Pascua', 6);
INSERT INTO PROVINCIA VALUES(16, 'Los Andes', 6);
INSERT INTO PROVINCIA VALUES(17, 'Petorca', 6);
INSERT INTO PROVINCIA VALUES(18, 'Quillota', 6);
INSERT INTO PROVINCIA VALUES(19, 'San Antonio', 6);
INSERT INTO PROVINCIA VALUES(20, 'San Felipe De Aconcagua', 6);
INSERT INTO PROVINCIA VALUES(21, 'Marga Marga', 6);

-- METROPOLITANA DE SANTIAGO
INSERT INTO PROVINCIA VALUES(22, 'Santiago', 7);
INSERT INTO PROVINCIA VALUES(23, 'Cordillera', 7);
INSERT INTO PROVINCIA VALUES(24, 'Chacabuco', 7);
INSERT INTO PROVINCIA VALUES(25, 'Maipo', 7);
INSERT INTO PROVINCIA VALUES(26, 'Melipilla', 7);
INSERT INTO PROVINCIA VALUES(27, 'Talagante', 7);

-- LIBERTADOR GENERAL BERNARDO O’HIGGINS
INSERT INTO PROVINCIA VALUES(28, 'Cachapoal', 8);
INSERT INTO PROVINCIA VALUES(29, 'Cardenal Caro', 8);
INSERT INTO PROVINCIA VALUES(30, 'Colchagua', 8);

-- MAULE
INSERT INTO PROVINCIA VALUES(31, 'Talca', 9);
INSERT INTO PROVINCIA VALUES(32, 'Cauquenes', 9);
INSERT INTO PROVINCIA VALUES(33, 'Curicó', 9);
INSERT INTO PROVINCIA VALUES(34, 'Linares', 9);

-- ÑUBLE
INSERT INTO PROVINCIA VALUES(35, 'Diguillín', 10);
INSERT INTO PROVINCIA VALUES(36, 'Punilla', 10);
INSERT INTO PROVINCIA VALUES(37, 'Itata', 10);

-- BIOBÍO
INSERT INTO PROVINCIA VALUES(38, 'Concepción', 11);
INSERT INTO PROVINCIA VALUES(39, 'Arauco', 11);
INSERT INTO PROVINCIA VALUES(40, 'Biobío', 11);

-- LA ARAUCANÍA
INSERT INTO PROVINCIA VALUES(41, 'Cautín', 12);
INSERT INTO PROVINCIA VALUES(42, 'Malleco', 12);

-- LOS RÍOS
INSERT INTO PROVINCIA VALUES(43, 'Valdivia', 13);
INSERT INTO PROVINCIA VALUES(44, 'Ranco', 13);

-- LOS LAGOS
INSERT INTO PROVINCIA VALUES(45, 'Llanquihue', 14);
INSERT INTO PROVINCIA VALUES(46, 'Chiloé', 14);
INSERT INTO PROVINCIA VALUES(47, 'Osorno', 14);
INSERT INTO PROVINCIA VALUES(48, 'Palena', 14);

-- AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO
INSERT INTO PROVINCIA VALUES(49, 'Coihaique', 15);
INSERT INTO PROVINCIA VALUES(50, 'Aisén', 15);
INSERT INTO PROVINCIA VALUES(51, 'Capitán Prat', 15);
INSERT INTO PROVINCIA VALUES(52, 'General Carrera', 15);

-- MAGALLANES Y LA ANTÁRTICA CHILENA
INSERT INTO PROVINCIA VALUES(53, 'Magallanes', 16);
INSERT INTO PROVINCIA VALUES(54, 'Antártica Chilena', 16);
INSERT INTO PROVINCIA VALUES(55, 'Tierra Del Fuego', 16);
INSERT INTO PROVINCIA VALUES(56, 'Ultima Esperanza', 16);


--------------------- COMUNAS POR PROVINCIA ---------------------
-- ARICA
INSERT INTO COMUNA VALUES(1, 'Arica', 1);
INSERT INTO COMUNA VALUES(2, 'Camarones', 1);

-- PARINACOTA
INSERT INTO COMUNA VALUES(3, 'Putre', 2);
INSERT INTO COMUNA VALUES(4, 'General Lagos', 2);

-- IQUIQUE
INSERT INTO COMUNA VALUES(5, 'Iquique', 3);
INSERT INTO COMUNA VALUES(6, 'Alto Hospicio', 3);

-- TAMARUGAL
INSERT INTO COMUNA VALUES(7, 'Pozo Almonte', 4);
INSERT INTO COMUNA VALUES(8, 'Camiña', 4);
INSERT INTO COMUNA VALUES(9, 'Colchane', 4);
INSERT INTO COMUNA VALUES(10, 'Huara', 4);
INSERT INTO COMUNA VALUES(11, 'Pica', 4);

-- ANTOFAGASTA
INSERT INTO COMUNA VALUES(12, 'Antofagasta', 5);
INSERT INTO COMUNA VALUES(13, 'Mejillones', 5);
INSERT INTO COMUNA VALUES(14, 'Sierra Gorda', 5);
INSERT INTO COMUNA VALUES(15, 'Taltal', 5);

-- EL LOA
INSERT INTO COMUNA VALUES(16, 'Calama', 6);
INSERT INTO COMUNA VALUES(17, 'Ollagüe', 6);
INSERT INTO COMUNA VALUES(18, 'San Pedro de Atacama', 6);

-- TOCOPILLA
INSERT INTO COMUNA VALUES(19, 'Tocopilla', 7);
INSERT INTO COMUNA VALUES(20, 'María Elena', 7);

-- COPIAPÓ
INSERT INTO COMUNA VALUES(21, 'Copiapó', 8);
INSERT INTO COMUNA VALUES(22, 'Caldera', 8);
INSERT INTO COMUNA VALUES(23, 'Tierra Amarilla', 8);

-- CHAÑARAL
INSERT INTO COMUNA VALUES(24, 'Chañaral', 9);
INSERT INTO COMUNA VALUES(25, 'Diego de Almagro', 9);

-- HUASCO
INSERT INTO COMUNA VALUES(26, 'Vallenar', 10);
INSERT INTO COMUNA VALUES(27, 'Alto del Carmen', 10);
INSERT INTO COMUNA VALUES(28, 'Freirina', 10);
INSERT INTO COMUNA VALUES(29, 'Huasco', 10);

-- ELQUI
INSERT INTO COMUNA VALUES(30, 'La Serena', 11);
INSERT INTO COMUNA VALUES(31, 'Coquimbo', 11);
INSERT INTO COMUNA VALUES(32, 'Andacollo', 11);
INSERT INTO COMUNA VALUES(33, 'La Higuera', 11);
INSERT INTO COMUNA VALUES(34, 'Paiguano', 11);
INSERT INTO COMUNA VALUES(35, 'Vicuña', 11);

-- CHOAPA
INSERT INTO COMUNA VALUES(36, 'Illapel', 12);
INSERT INTO COMUNA VALUES(37, 'Canela', 12);
INSERT INTO COMUNA VALUES(38, 'Los Vilos', 12);
INSERT INTO COMUNA VALUES(39, 'Salamanca', 12);

-- LIMARÍ
INSERT INTO COMUNA VALUES(40, 'Ovalle', 13);
INSERT INTO COMUNA VALUES(41, 'Combarbalá', 13);
INSERT INTO COMUNA VALUES(42, 'Monte Patria', 13);
INSERT INTO COMUNA VALUES(43, 'Punitaqui', 13);
INSERT INTO COMUNA VALUES(44, 'Río Hurtado', 13);

-- VALPARAÍSO
INSERT INTO COMUNA VALUES(45, 'Valparaíso', 14);
INSERT INTO COMUNA VALUES(46, 'Casablanca', 14);
INSERT INTO COMUNA VALUES(47, 'Concón', 14);
INSERT INTO COMUNA VALUES(48, 'Juan Fernández', 14);
INSERT INTO COMUNA VALUES(49, 'Puchuncaví', 14);
INSERT INTO COMUNA VALUES(50, 'Quintero', 14);
INSERT INTO COMUNA VALUES(51, 'Viña del Mar', 14);

-- ISLA DE PASCUA 
INSERT INTO COMUNA VALUES(52, 'Isla de Pascua', 15);

-- LOS ANDES
INSERT INTO COMUNA VALUES(53, 'Los Andes', 16);
INSERT INTO COMUNA VALUES(54, 'Calle Larga', 16);
INSERT INTO COMUNA VALUES(55, 'Rinconada', 16);
INSERT INTO COMUNA VALUES(56, 'San Esteban', 16);

-- PETORCA
INSERT INTO COMUNA VALUES(57, 'La Ligua', 17);
INSERT INTO COMUNA VALUES(58, 'Cabildo', 17);
INSERT INTO COMUNA VALUES(59, 'Papudo', 17);
INSERT INTO COMUNA VALUES(60, 'Petorca', 17);
INSERT INTO COMUNA VALUES(61, 'Zapallar', 17);

-- QUILLOTA
INSERT INTO COMUNA VALUES(62, 'Quillota', 18);
INSERT INTO COMUNA VALUES(63, 'Calera', 18);
INSERT INTO COMUNA VALUES(64, 'Hijuelas', 18);
INSERT INTO COMUNA VALUES(65, 'La Cruz', 18);
INSERT INTO COMUNA VALUES(66, 'Nogales', 18);

-- SAN ANTONIO 
INSERT INTO COMUNA VALUES(67, 'San Antonio', 19);
INSERT INTO COMUNA VALUES(68, 'Algarrobo', 19);
INSERT INTO COMUNA VALUES(69, 'Cartagena', 19);
INSERT INTO COMUNA VALUES(70, 'El Quisco', 19);
INSERT INTO COMUNA VALUES(71, 'El Tabo', 19);
INSERT INTO COMUNA VALUES(72, 'Santo Domingo', 19);

-- SAN FELIPE DE ACONCAGUA
INSERT INTO COMUNA VALUES(73, 'San Felipe', 20);
INSERT INTO COMUNA VALUES(74, 'Catemu', 20);
INSERT INTO COMUNA VALUES(75, 'Llaillay', 20);
INSERT INTO COMUNA VALUES(76, 'Panquehue', 20);
INSERT INTO COMUNA VALUES(77, 'Putaendo', 20);
INSERT INTO COMUNA VALUES(78, 'Santa María', 20);

-- MARGA MARGA
INSERT INTO COMUNA VALUES(79, 'Limache', 21);
INSERT INTO COMUNA VALUES(80, 'Quilpué', 21);
INSERT INTO COMUNA VALUES(81, 'Villa Alemana', 21);
INSERT INTO COMUNA VALUES(82, 'Olmué', 21);

-- SANTIAGO
INSERT INTO COMUNA VALUES(83, 'Santiago', 22);
INSERT INTO COMUNA VALUES(84, 'Cerrillos', 22);
INSERT INTO COMUNA VALUES(85, 'Cerro Navia', 22);
INSERT INTO COMUNA VALUES(86, 'Conchalí', 22);
INSERT INTO COMUNA VALUES(87, 'El Bosque', 22);
INSERT INTO COMUNA VALUES(88, 'Estación Central', 22);
INSERT INTO COMUNA VALUES(89, 'Huechuraba', 22);
INSERT INTO COMUNA VALUES(90, 'Independencia', 22);
INSERT INTO COMUNA VALUES(91, 'La Cisterna', 22);
INSERT INTO COMUNA VALUES(92, 'La Florida', 22);
INSERT INTO COMUNA VALUES(93, 'La Granja', 22);
INSERT INTO COMUNA VALUES(94, 'La Pintana', 22);
INSERT INTO COMUNA VALUES(95, 'La Reina', 22);
INSERT INTO COMUNA VALUES(96, 'Las Condes', 22);
INSERT INTO COMUNA VALUES(97, 'Lo Barnechea', 22);
INSERT INTO COMUNA VALUES(98, 'Lo Espejo', 22);
INSERT INTO COMUNA VALUES(99, 'Lo Prado', 22);
INSERT INTO COMUNA VALUES(100, 'Macul', 22);
INSERT INTO COMUNA VALUES(101, 'Maipú', 22);
INSERT INTO COMUNA VALUES(102, 'Ñuñoa', 22);
INSERT INTO COMUNA VALUES(103, 'Pedro Aguirre Cerda', 22);
INSERT INTO COMUNA VALUES(104, 'Peñalolén', 22);
INSERT INTO COMUNA VALUES(105, 'Providencia', 22);
INSERT INTO COMUNA VALUES(106, 'Pudahuel', 22);
INSERT INTO COMUNA VALUES(107, 'Quilicura', 22);
INSERT INTO COMUNA VALUES(108, 'Quinta Normal', 22);
INSERT INTO COMUNA VALUES(109, 'Recoleta', 22);
INSERT INTO COMUNA VALUES(110, 'Renca', 22);
INSERT INTO COMUNA VALUES(111, 'Joaquín', 22);
INSERT INTO COMUNA VALUES(112, 'San Miguel', 22);
INSERT INTO COMUNA VALUES(113, 'San Ramón', 22);
INSERT INTO COMUNA VALUES(114, 'Vitacura', 22);

-- CORDILLERA
INSERT INTO COMUNA VALUES(115, 'Puente Alto', 23);
INSERT INTO COMUNA VALUES(116, 'Pirque', 23);
INSERT INTO COMUNA VALUES(117, 'San José de Maipú', 23);

-- CHACABUCO
INSERT INTO COMUNA VALUES(118, 'Colina', 24);
INSERT INTO COMUNA VALUES(119, 'Lampa', 24);
INSERT INTO COMUNA VALUES(120, 'Tiltil', 24);

-- MAIPO
INSERT INTO COMUNA VALUES(121, 'San Bernardo', 25);
INSERT INTO COMUNA VALUES(122, 'Buin', 25);
INSERT INTO COMUNA VALUES(123, 'Calera de Tango', 25);
INSERT INTO COMUNA VALUES(124, 'Paine', 25);

-- MELIPILLA
INSERT INTO COMUNA VALUES(125, 'Melipilla', 26);
INSERT INTO COMUNA VALUES(126, 'Alhué', 26);
INSERT INTO COMUNA VALUES(127, 'Curacaví', 26);
INSERT INTO COMUNA VALUES(128, 'María Pinto', 26);
INSERT INTO COMUNA VALUES(129, 'San Pedro', 26);

-- TALAGANTE
INSERT INTO COMUNA VALUES(130, 'Talagante', 27);
INSERT INTO COMUNA VALUES(131, 'El Monte', 27);
INSERT INTO COMUNA VALUES(132, 'Isla de Maipo', 27);
INSERT INTO COMUNA VALUES(133, 'Padre Hurtado', 27);
INSERT INTO COMUNA VALUES(134, 'Peñaflor', 27);

-- CACHAPOAL
INSERT INTO COMUNA VALUES(135, 'Rancagua', 28);
INSERT INTO COMUNA VALUES(136, 'Codegua', 28);
INSERT INTO COMUNA VALUES(137, 'Coinco', 28);
INSERT INTO COMUNA VALUES(138, 'Coltauco', 28);
INSERT INTO COMUNA VALUES(139, 'Doñihue', 28);
INSERT INTO COMUNA VALUES(140, 'Graneros', 28);
INSERT INTO COMUNA VALUES(141, 'Las Cabras', 28);
INSERT INTO COMUNA VALUES(142, 'Machalí', 28);
INSERT INTO COMUNA VALUES(143, 'Malloa', 28);
INSERT INTO COMUNA VALUES(144, 'Mostazal', 28);
INSERT INTO COMUNA VALUES(145, 'Olivar', 28);
INSERT INTO COMUNA VALUES(146, 'Peumo', 28);
INSERT INTO COMUNA VALUES(147, 'Pichidegua', 28);
INSERT INTO COMUNA VALUES(148, 'Quinta de Tilcoco', 28);
INSERT INTO COMUNA VALUES(149, 'Rengo', 28);
INSERT INTO COMUNA VALUES(150, 'Requínoa', 28);
INSERT INTO COMUNA VALUES(151, 'San Vicente', 28);

-- CARDENAL CARO 
INSERT INTO COMUNA VALUES(152, 'Pichilemu', 29);
INSERT INTO COMUNA VALUES(153, 'La Estrella', 29);
INSERT INTO COMUNA VALUES(154, 'Litueche', 29);
INSERT INTO COMUNA VALUES(155, 'Marchihue', 29);
INSERT INTO COMUNA VALUES(156, 'Navidad', 29);
INSERT INTO COMUNA VALUES(157, 'Paredones', 29);

-- COLCHAGUA
INSERT INTO COMUNA VALUES(158, 'San Fernando', 30);
INSERT INTO COMUNA VALUES(159, 'Chépica', 30);
INSERT INTO COMUNA VALUES(160, 'Chimbarongo', 30);
INSERT INTO COMUNA VALUES(161, 'Lolol', 30);
INSERT INTO COMUNA VALUES(162, 'Nancagua', 30);
INSERT INTO COMUNA VALUES(163, 'Palmilla', 30);
INSERT INTO COMUNA VALUES(164, 'Peralillo', 30);
INSERT INTO COMUNA VALUES(165, 'Placilla', 30);
INSERT INTO COMUNA VALUES(166, 'Pumanque', 30);
INSERT INTO COMUNA VALUES(167, 'Santa Cruz', 30);

-- TALCA
INSERT INTO COMUNA VALUES(168, 'Talca', 31);
INSERT INTO COMUNA VALUES(169, 'Constitución', 31);
INSERT INTO COMUNA VALUES(170, 'Curepto', 31);
INSERT INTO COMUNA VALUES(171, 'Empedrado', 31);
INSERT INTO COMUNA VALUES(172, 'Maule', 31);
INSERT INTO COMUNA VALUES(173, 'Pelarco', 31);
INSERT INTO COMUNA VALUES(174, 'Pencahue', 31);
INSERT INTO COMUNA VALUES(175, 'Río Claro', 31);
INSERT INTO COMUNA VALUES(176, 'San Clemente', 31);
INSERT INTO COMUNA VALUES(177, 'San Rafael', 31);

-- CAUQUENES
INSERT INTO COMUNA VALUES(178, 'Cauquenes', 32);
INSERT INTO COMUNA VALUES(179, 'Chanco', 32);
INSERT INTO COMUNA VALUES(180, 'Pelluhue', 32);

-- CURICÓ
INSERT INTO COMUNA VALUES(181, 'Curicó', 33);
INSERT INTO COMUNA VALUES(182, 'Hualañé', 33);
INSERT INTO COMUNA VALUES(183, 'Licantén', 33);
INSERT INTO COMUNA VALUES(184, 'Molina', 33);
INSERT INTO COMUNA VALUES(185, 'Rauco', 33);
INSERT INTO COMUNA VALUES(186, 'Romeral', 33);
INSERT INTO COMUNA VALUES(187, 'Sagrada Familia', 33);
INSERT INTO COMUNA VALUES(188, 'Teno', 33);
INSERT INTO COMUNA VALUES(189, 'Vichuquén', 33);

-- LINARES
INSERT INTO COMUNA VALUES(190, 'Linares', 34);
INSERT INTO COMUNA VALUES(191, 'Colbún', 34);
INSERT INTO COMUNA VALUES(192, 'Longaví', 34);
INSERT INTO COMUNA VALUES(193, 'Parral', 34);
INSERT INTO COMUNA VALUES(194, 'Retiro', 34);
INSERT INTO COMUNA VALUES(195, 'San Javier', 34);
INSERT INTO COMUNA VALUES(196, 'Villa Alegre', 34);
INSERT INTO COMUNA VALUES(197, 'Yerbas Buenas', 34);

-- DIGUILLÍN
INSERT INTO COMUNA VALUES(198, 'Bulnes', 35);
INSERT INTO COMUNA VALUES(199, 'Chillán Viejo', 35);
INSERT INTO COMUNA VALUES(200, 'Chillán', 35);
INSERT INTO COMUNA VALUES(201, 'El Carmen', 35);
INSERT INTO COMUNA VALUES(202, 'Pemuco', 35);
INSERT INTO COMUNA VALUES(203, 'Pinto', 35);
INSERT INTO COMUNA VALUES(204, 'Quillón', 35);
INSERT INTO COMUNA VALUES(205, 'San Ignacio', 35);
INSERT INTO COMUNA VALUES(206, 'Yungay', 35);

-- PUNILLA
INSERT INTO COMUNA VALUES(207, 'Coihueco', 36);
INSERT INTO COMUNA VALUES(208, 'Ñiquén', 36);
INSERT INTO COMUNA VALUES(209, 'San Carlos', 36);
INSERT INTO COMUNA VALUES(210, 'San Fabián', 36);
INSERT INTO COMUNA VALUES(211, 'San Nicolás', 36);

-- ITATA
INSERT INTO COMUNA VALUES(212, 'Cobquecura', 37);
INSERT INTO COMUNA VALUES(213, 'Coelemu', 37);
INSERT INTO COMUNA VALUES(214, 'Ninhue', 37);
INSERT INTO COMUNA VALUES(215, 'Portezuelo', 37);
INSERT INTO COMUNA VALUES(216, 'Quirihue', 37);
INSERT INTO COMUNA VALUES(217, 'Ránquil', 37);
INSERT INTO COMUNA VALUES(218, 'Trehuaco', 37);

-- CONCEPCIÓN
INSERT INTO COMUNA VALUES(219, 'Concepción', 38);
INSERT INTO COMUNA VALUES(220, 'Coronel', 38);
INSERT INTO COMUNA VALUES(221, 'Chiguayante', 38);
INSERT INTO COMUNA VALUES(222, 'Florida', 38);
INSERT INTO COMUNA VALUES(223, 'Hualqui', 38);
INSERT INTO COMUNA VALUES(224, 'Lota', 38);
INSERT INTO COMUNA VALUES(225, 'Penco', 38);
INSERT INTO COMUNA VALUES(226, 'San Pedro de la Paz', 38);
INSERT INTO COMUNA VALUES(227, 'Santa Juana', 38);
INSERT INTO COMUNA VALUES(228, 'Talcahuano', 38);
INSERT INTO COMUNA VALUES(229, 'Tomé', 38);
INSERT INTO COMUNA VALUES(230, 'Hualpén', 38);

-- ARAUCO
INSERT INTO COMUNA VALUES(231, 'Lebu', 39);
INSERT INTO COMUNA VALUES(232, 'Arauco', 39);
INSERT INTO COMUNA VALUES(233, 'Cañete', 39);
INSERT INTO COMUNA VALUES(234, 'Contulmo', 39);
INSERT INTO COMUNA VALUES(235, 'Curanilahue', 39);
INSERT INTO COMUNA VALUES(236, 'Los Alamos', 39);
INSERT INTO COMUNA VALUES(237, 'Tirúa', 39);

-- BIOBÍO
INSERT INTO COMUNA VALUES(238, 'Los Angeles', 40);
INSERT INTO COMUNA VALUES(239, 'Antuco', 40);
INSERT INTO COMUNA VALUES(240, 'Cabrero', 40);
INSERT INTO COMUNA VALUES(241, 'Laja', 40);
INSERT INTO COMUNA VALUES(242, 'Mulchén', 40);
INSERT INTO COMUNA VALUES(243, 'Nacimiento', 40);
INSERT INTO COMUNA VALUES(244, 'Negrete', 40);
INSERT INTO COMUNA VALUES(245, 'Quilaco', 40);
INSERT INTO COMUNA VALUES(246, 'Quilleco', 40);
INSERT INTO COMUNA VALUES(247, 'San Rosendo', 40);
INSERT INTO COMUNA VALUES(248, 'Santa Bárbara', 40);
INSERT INTO COMUNA VALUES(249, 'Tucapel', 40);
INSERT INTO COMUNA VALUES(250, 'Yumbel', 40);
INSERT INTO COMUNA VALUES(251, 'Alto Biobío', 40);

-- CAUTÍN
INSERT INTO COMUNA VALUES(252, 'Temuco', 41);
INSERT INTO COMUNA VALUES(253, 'Carahue', 41);
INSERT INTO COMUNA VALUES(254, 'Cunco', 41);
INSERT INTO COMUNA VALUES(255, 'Curarrehue', 41);
INSERT INTO COMUNA VALUES(256, 'Freire', 41);
INSERT INTO COMUNA VALUES(257, 'Galvarino', 41);
INSERT INTO COMUNA VALUES(258, 'Gorbea', 41);
INSERT INTO COMUNA VALUES(259, 'Lautaro', 41);
INSERT INTO COMUNA VALUES(260, 'Loncoche', 41);
INSERT INTO COMUNA VALUES(261, 'Melipeuco', 41);
INSERT INTO COMUNA VALUES(262, 'Nueva Imperial', 41);
INSERT INTO COMUNA VALUES(263, 'Padre Las Casas', 41);
INSERT INTO COMUNA VALUES(264, 'Perquenco', 41);
INSERT INTO COMUNA VALUES(265, 'Pitrufquén', 41);
INSERT INTO COMUNA VALUES(266, 'Pucón', 41);
INSERT INTO COMUNA VALUES(267, 'Saavedra', 41);
INSERT INTO COMUNA VALUES(268, 'Teodoro Schmidt', 41);
INSERT INTO COMUNA VALUES(269, 'Toltén', 41);
INSERT INTO COMUNA VALUES(270, 'Vilcún', 41);
INSERT INTO COMUNA VALUES(271, 'Villarrica', 41);
INSERT INTO COMUNA VALUES(272, 'Cholchol', 41);

-- MALLECO
INSERT INTO COMUNA VALUES(273, 'Angol', 42);
INSERT INTO COMUNA VALUES(274, 'Collipulli', 42);
INSERT INTO COMUNA VALUES(275, 'Curacautín', 42);
INSERT INTO COMUNA VALUES(276, 'Ercilla', 42);
INSERT INTO COMUNA VALUES(277, 'Lonquimay', 42);
INSERT INTO COMUNA VALUES(278, 'Los Sauces', 42);
INSERT INTO COMUNA VALUES(279, 'Lumaco', 42);
INSERT INTO COMUNA VALUES(280, 'Purén', 42);
INSERT INTO COMUNA VALUES(281, 'Renaico', 42);
INSERT INTO COMUNA VALUES(282, 'Traiguén', 42);
INSERT INTO COMUNA VALUES(283, 'Victoria', 42);

-- VALDIVIA
INSERT INTO COMUNA VALUES(284, 'Valdivia', 43);
INSERT INTO COMUNA VALUES(285, 'Corral', 43);
INSERT INTO COMUNA VALUES(286, 'Lanco', 43);
INSERT INTO COMUNA VALUES(287, 'Los Lagos', 43);
INSERT INTO COMUNA VALUES(288, 'Máfil', 43);
INSERT INTO COMUNA VALUES(289, 'Mariquina', 43);
INSERT INTO COMUNA VALUES(290, 'Paillaco', 43);
INSERT INTO COMUNA VALUES(291, 'Panguipulli', 43);

-- RANCO
INSERT INTO COMUNA VALUES(292, 'La Unión', 44);
INSERT INTO COMUNA VALUES(293, 'Futrono', 44);
INSERT INTO COMUNA VALUES(294, 'Lago Ranco', 44);
INSERT INTO COMUNA VALUES(295, 'Río Bueno', 44);

-- LLANQUIHUE 
INSERT INTO COMUNA VALUES(296, 'Puerto Montt', 45);
INSERT INTO COMUNA VALUES(297, 'Calbuco', 45);
INSERT INTO COMUNA VALUES(298, 'Cochamó', 45);
INSERT INTO COMUNA VALUES(299, 'Fresia', 45);
INSERT INTO COMUNA VALUES(300, 'Frutillar', 45);
INSERT INTO COMUNA VALUES(301, 'Los Muermos', 45);
INSERT INTO COMUNA VALUES(302, 'Llanquihue', 45);
INSERT INTO COMUNA VALUES(303, 'Maullín', 45);
INSERT INTO COMUNA VALUES(304, 'Puerto Varas', 45);

-- CHILOÉ
INSERT INTO COMUNA VALUES(305, 'Castro', 46);
INSERT INTO COMUNA VALUES(306, 'Ancud', 46);
INSERT INTO COMUNA VALUES(307, 'Chonchi', 46);
INSERT INTO COMUNA VALUES(308, 'Curaco de Vélez', 46);
INSERT INTO COMUNA VALUES(309, 'Dalcahue', 46);
INSERT INTO COMUNA VALUES(310, 'Puqueldón', 46);
INSERT INTO COMUNA VALUES(311, 'Queilén', 46);
INSERT INTO COMUNA VALUES(312, 'Quellón', 46);
INSERT INTO COMUNA VALUES(313, 'Quemchi', 46);
INSERT INTO COMUNA VALUES(314, 'Quinchao', 46);

-- OSORNO
INSERT INTO COMUNA VALUES(315, 'Osorno', 47);
INSERT INTO COMUNA VALUES(316, 'Puerto Octay', 47);
INSERT INTO COMUNA VALUES(317, 'Purranque', 47);
INSERT INTO COMUNA VALUES(318, 'Puyehue', 47);
INSERT INTO COMUNA VALUES(319, 'Río Negro', 47);
INSERT INTO COMUNA VALUES(320, 'San Juan de la Costa', 47);
INSERT INTO COMUNA VALUES(321, 'San Pablo', 47);

-- PALENA
INSERT INTO COMUNA VALUES(322, 'Chaitén', 48);
INSERT INTO COMUNA VALUES(323, 'Futaleufú', 48);
INSERT INTO COMUNA VALUES(324, 'Hualaihué', 48);
INSERT INTO COMUNA VALUES(325, 'Palena', 48);

-- COIHAIQUE
INSERT INTO COMUNA VALUES(326, 'Coihaique', 49);
INSERT INTO COMUNA VALUES(327, 'Lago Verde', 49);

-- AISÉN
INSERT INTO COMUNA VALUES(328, 'Aysén', 50);
INSERT INTO COMUNA VALUES(329, 'Cisnes', 50);
INSERT INTO COMUNA VALUES(330, 'Guaitecas', 50);

-- CAPITÁN PRAT
INSERT INTO COMUNA VALUES(331, 'Cochrane', 51);
INSERT INTO COMUNA VALUES(332, 'OHiggins', 51);
INSERT INTO COMUNA VALUES(333, 'Tortel', 51);

-- GENERAL CARRERA
INSERT INTO COMUNA VALUES(334, 'Chile Chico', 52);
INSERT INTO COMUNA VALUES(335, 'Río Ibáñez', 52);

-- MAGALLANES
INSERT INTO COMUNA VALUES(336, 'Punta Arenas', 53);
INSERT INTO COMUNA VALUES(337, 'Laguna Blanca', 53);
INSERT INTO COMUNA VALUES(338, 'Río Verde', 53);
INSERT INTO COMUNA VALUES(339, 'San Gregorio', 53);

-- ANTÁRTICA
INSERT INTO COMUNA VALUES(340, 'Cabo de Hornos', 54);
INSERT INTO COMUNA VALUES(341, 'Antártica', 54);

-- TIERRA DEL FUEGO
INSERT INTO COMUNA VALUES(342, 'Porvenir', 55);
INSERT INTO COMUNA VALUES(343, 'Primavera', 55);
INSERT INTO COMUNA VALUES(344, 'Timaukel', 55);

-- ULTIMA ESPERANZA
INSERT INTO COMUNA VALUES(345, 'Natales', 56);
INSERT INTO COMUNA VALUES(346, 'Torres del Paine', 56);

COMMIT;